#!/bin/bash
set -euo pipefail

# ─── Uptime Kuma Monitor Setup ───────────────────────────
# Run after first Uptime Kuma boot to create monitors.
# Requires: KUMA_URL, KUMA_USERNAME, KUMA_PASSWORD
# ──────────────────────────────────────────────────────────

KUMA_URL="${KUMA_URL:-http://localhost:3001}"
KUMA_USERNAME="${KUMA_USERNAME:-admin}"
KUMA_PASSWORD="${KUMA_PASSWORD:-admin}"
NTFY_URL="${NTFY_URL:-https://ntfy.hiten-patel.co.uk/system}"
APP_URL="${APP_URL:-http://ironpulse:3000}"

echo "=== Uptime Kuma Monitor Setup ==="
echo "Kuma URL: $KUMA_URL"
echo ""
echo "This script sets up monitors after the first Uptime Kuma boot."
echo "You must first:"
echo "  1. Open $KUMA_URL in a browser"
echo "  2. Create the admin account (username: $KUMA_USERNAME)"
echo "  3. Add an ntfy notification provider in Settings > Notifications"
echo "     - Type: ntfy"
echo "     - Server URL: https://ntfy.hiten-patel.co.uk"
echo "     - Topic: system"
echo ""
echo "Then configure these monitors manually:"
echo ""
echo "  Monitor 1: IronPulse App"
echo "    Type: HTTP(s)"
echo "    URL: $APP_URL/api/health"
echo "    Interval: 60s"
echo "    Keyword: \"ok\""
echo ""
echo "  Monitor 2: PostgreSQL"
echo "    Type: TCP Port"
echo "    Host: postgres"
echo "    Port: 5432"
echo "    Interval: 60s"
echo ""
echo "  Monitor 3: Redis"
echo "    Type: TCP Port"
echo "    Host: redis"
echo "    Port: 6379"
echo "    Interval: 60s"
echo ""
echo "  Monitor 4: MinIO"
echo "    Type: HTTP(s)"
echo "    URL: http://minio:9000/minio/health/live"
echo "    Interval: 120s"
echo ""
echo "  Monitor 5: PowerSync"
echo "    Type: TCP Port"
echo "    Host: powersync"
echo "    Port: 80"
echo "    Interval: 120s"
echo ""
echo "Uptime Kuma doesn't have a stable REST API for automated setup."
echo "Use the web UI at $KUMA_URL to configure monitors."
