FROM journeyapps/powersync-service:latest@sha256:b6b22fa7d0d862f04bdff62846e656756d17bcf3dd6eca399a0633671051438b

COPY powersync.yaml /app/powersync.yaml
COPY sync-rules.yaml /app/config/sync-rules.yaml
